/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import okhttp3.ResponseBody
import retrofit2.Call
import retrofit2.Retrofit
import retrofit2.http.GET

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    var status = 0
    Retrofit.Builder().baseUrl("https://example.com/").build().create(Ser::class.java).get().enqueue(object: retrofit2.Callback<ResponseBody> {
        override fun onResponse(call: Call<ResponseBody>, response: retrofit2.Response<ResponseBody>) {
            println("Success: ${response.body()}")
            println("${response.body()?.string()}")
        }

        override fun onFailure(call: Call<ResponseBody>, t: Throwable) {
            println("Failure: ${t.message}")
            status = 1
        }
    })
    //System.exit(status)
}

interface Ser {
    @GET("/")
    fun get() : Call<ResponseBody>
}